config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'
  } # CSRF_forgery makes this fail :3

  resources :users

  # -- Lessons

  resources :lessons do
    member do
      delete :delete
      put :publish
      post :upload_file, as: :upload_file_for
      post :delete_file, as: :delete_file_for
      get 'show' => 'lessons#show', as: 'lesson_path' # a dummy route to show dummy lesson
    end
    resources :steps do
      post :upload_file, as: :upload_file
      post :delete_file, as: :delete_file
    end
    resources :standards
  end

  resources :people
  resources :places

  get 'search' => 'search#index'


  #get  'lessons/new' => 'lessons#new', as: :lesson_new
  # post 'lessons'            => 'lessons#create'#, as: :lesson_create
  #post 'lessons/new'            => 'lessons#new', as: :lesson_create
  # the above line is strictly used for the weekend of the 13/7/2017 for submit on new page loads

  #get 'lessons/test'  => 'lessons#test', as: :lesson_test

  #post '/lessons/:id/publish' => 'lessons#publis', as: :lesson_publish#--
  #put  'lessons/:id'        => 'lessons#update'
  #delete 'lessons/:id' => 'lessons#delete', as: :lesson_delete #--

  #post 'lessons/:id/step'   => 'lessons#add_step'

  #delete 'lessons/:id/step/:step_id'   => 'lessons#delete_step'

  #get 'lessons/:id/file/:attr', to: 'lessons#file_upload_load', as: :lesson_file_data
  #post 'lessons/:id/file/:attr', to: 'lessons#file_upload', as: :lesson_file
  #delete 'lessons/:id/file', to: 'lessons#remove_file_upload', as: :delete_lesson_file
  #~~~~~~~~~~

  #get 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload_load', as: :lesson_step_file_data
  #post 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload', as: :step_file
  #delete 'lessons/:id/:step/file', to: 'lessons#step_remove_file_upload', as: :delete_step_file

  #get 'lessons/:id'        => 'lessons_public#show', as: :lesson_view
  #get 'list/lessons'  => 'lessons_public#list', as: :lesson_list

  #~~~~ Steps Ajax
  #put     'lessons/:id/steps' => 'lessons#set_steps'
  #delete  'lessons/:id/steps' => 'lessons#remove_step'
  #~~~~~~~~~~

  # -- .Lessons

  get 'file_form'         => 'visitors#form'
  post 'file_upload'      => 'visitors#file_form_upload',  as: :lesson_file_test

  post 'register' => 'visitors#register_interest', as: :register

  post 'users/affiliate' => 'users#affiliate_organization_id'

  get 'api/users/exists'   =>  'secured_api#user_presence'

  #get 'search/:entity', :to => 'search#main', as: :search

  # Static pages
  get 'enter' =>  'visitors#enter', as: :enter
  get 'about' => 'visitors#about', as: :about
  get 'policy' => 'visitors#policy', as: :policy
  get 'get_involved' => 'visitors#get_involved', as: :involved

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index

    # Pagination stub, just so i can style the output - DH
    @paginatable_array = Kaminari.paginate_array([*1..280]).page(params[:page]).per(12)

  end

  def show

    # Person obj
    @person_obj = User.first

    set_person_sections

    # Fetch any specified section and turn it into a sym, otherwise :overview
    @section = params[:section].present? ? params[:section].to_sym : :overview

  end


end

app/views/people/_filter_overlay.html.erb
<div class="FilterOverlay FilterOverlay--active">

  <button class="FilterOverlay__close"><span>✕</span></button>

  <div class="FilterOverlay__content">

    <%= form_tag(people_path, method: :get, class: "Form") do %>

      <%= field_set_tag nil, class: 'Form__fieldset' do %>

        

        <div class="Form__actions">
          <button type="submit" class="Button Button--primary Button--right Button--icon Button--icon--check">Apply filters</button>
        </div>

      <% end %>

    <% end %>

  </div>

</div>

app/views/people/_show_sub_nav.html.erb
<!-- sub navigation -->
<div class="SubNavigation">

  <div class="SubNavigation__content">

    <div class="SubNavigation__items">

      <%= active_link_to "Overview", person_path(id: 1, section: :overview),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :overview %>

      <%= active_link_to "Lessons", person_path(id: 1, section: :lessons),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :lessons %>

      <%= prev_person_section(@section).present? ? link_to(content_tag(:span, "Prev"), prev_person_section(@section), class: "SubNavigation__nav SubNavigation__nav--prev") : nil %>
      <%= next_person_section(@section).present? ? link_to(content_tag(:span, "Next"), next_person_section(@section), class: "SubNavigation__nav SubNavigation__nav--next") : nil %>

      <div class="SubNavigation__dots">
        <% @person_sections.each do |name, path| %>
        <%= name != @section ? link_to("•", path, class: "SubNavigation__dot") : content_tag(:span, "•", class: "SubNavigation__dot") %>
        <% end %>
      </div>

    </div>

    <div class="SubNavigation__actions">
      <%= link_to "Follow Daniel", '#', class: "Button Button--small Button--icon Button--icon--edit" %>
    </div>

  </div>

</div>

app/views/people/index.html.erb
<div class="Filter">

  <div class="Filter__content">

    <a href="" class="Filter__sort">
      <div class="Filter__sort__label">
        Sort by:
      </div>
      <div class="Filter__sort__selected">
        Date registered
      </div>
    </a>

    <a href="" class="Filter__filters">
      <div class="Filter__filters__label">
        Filter
      </div>
      <div class="Filter__filters__selected">
        <span>2</span>
      </div>
    </a>

  </div>

</div>

<%= render partial: "people/filter_overlay" %>

<div class="List List--people">

    <% 20.times do |i| %>
    <a href="<%= person_path(i) %>" class="List__item">

        <div class="List__avatar">
            <img src="<%= image_url("avatars/avatar#{i.odd? ? 1 : 2}.jpg") %>" class="Image Image--lazy" />
        </div>

        <div class="List__name">
            <%= Faker::Name.name %>
        </div>

    </a>
    <% end %>

</div>

<%= paginate @paginatable_array %>

app/views/people/show.html.erb
<%= render partial: 'people/show_sub_nav' %>

<%= render partial: 'people/show/header' %>

<%= render partial: "people/show/#{@section}" %>