config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'
  } # CSRF_forgery makes this fail :3

  resources :users

  # -- Lessons

  resources :lessons do
    member do
      delete :delete
      put :publish
      post :upload_file, as: :upload_file_for
      post :delete_file, as: :delete_file_for
      get 'show' => 'lessons#show', as: 'lesson_path' # a dummy route to show dummy lesson
    end
    resources :steps do
      post :upload_file, as: :upload_file
      post :delete_file, as: :delete_file
    end
    resources :standards
  end

  resources :people
  resources :places

  get 'search' => 'search#index'


  #get  'lessons/new' => 'lessons#new', as: :lesson_new
  # post 'lessons'            => 'lessons#create'#, as: :lesson_create
  #post 'lessons/new'            => 'lessons#new', as: :lesson_create
  # the above line is strictly used for the weekend of the 13/7/2017 for submit on new page loads

  #get 'lessons/test'  => 'lessons#test', as: :lesson_test

  #post '/lessons/:id/publish' => 'lessons#publis', as: :lesson_publish#--
  #put  'lessons/:id'        => 'lessons#update'
  #delete 'lessons/:id' => 'lessons#delete', as: :lesson_delete #--

  #post 'lessons/:id/step'   => 'lessons#add_step'

  #delete 'lessons/:id/step/:step_id'   => 'lessons#delete_step'

  #get 'lessons/:id/file/:attr', to: 'lessons#file_upload_load', as: :lesson_file_data
  #post 'lessons/:id/file/:attr', to: 'lessons#file_upload', as: :lesson_file
  #delete 'lessons/:id/file', to: 'lessons#remove_file_upload', as: :delete_lesson_file
  #~~~~~~~~~~

  #get 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload_load', as: :lesson_step_file_data
  #post 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload', as: :step_file
  #delete 'lessons/:id/:step/file', to: 'lessons#step_remove_file_upload', as: :delete_step_file

  #get 'lessons/:id'        => 'lessons_public#show', as: :lesson_view
  #get 'list/lessons'  => 'lessons_public#list', as: :lesson_list

  #~~~~ Steps Ajax
  #put     'lessons/:id/steps' => 'lessons#set_steps'
  #delete  'lessons/:id/steps' => 'lessons#remove_step'
  #~~~~~~~~~~

  # -- .Lessons

  get 'file_form'         => 'visitors#form'
  post 'file_upload'      => 'visitors#file_form_upload',  as: :lesson_file_test

  post 'register' => 'visitors#register_interest', as: :register

  post 'users/affiliate' => 'users#affiliate_organization_id'

  get 'api/users/exists'   =>  'secured_api#user_presence'

  #get 'search/:entity', :to => 'search#main', as: :search

  # Static pages
  get 'enter' =>  'visitors#enter', as: :enter
  get 'about' => 'visitors#about', as: :about
  get 'policy' => 'visitors#policy', as: :policy
  get 'get_involved' => 'visitors#get_involved', as: :involved

end

app/controllers/lessons_controller.rb
# frozen_string_literal: true
class LessonsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :update, :delete_file, :upload_file, :publish]
  #skip_before_action :verify_authenticity_token

  before_action :set_lesson, only: [:show, :activity]
  before_action :set_contexts, only: [:index, :edit]
  before_action :set_subjects, only: [:index, :edit]
  before_action :set_collections, only: [:index, :edit]
  before_action :set_fabrication_tools, only: [:index, :edit]

  def index
    # Using lessons#index for now as the public view of all lesson
    # No authentication heres

    # Fetch the page number, otherwise 1
    @page = params[:page] || 1

    param = filter_params[:lesson]


    @lessons = Lesson.includes(:steps).visible

    @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "CollectionTag"}).where(lesson_tags: {taggable: param[:collection_tag]}) if param[:collection_tag].present?

    param[:subjects].map{|x|
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "Subject"}).where(lesson_tags: {taggable: x})
    } if param[:subjects].present?

    param[:contexts].map{|x|
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "Subject"}).where(lesson_tags: {taggable: x})
    } if param[:contexts].present?

    if param[:teaching_range].present?
      lower = param[:teaching_range][:start]
      higher = param[:teaching_range][:end]
      t = TeachingRange.where(range_start: lower+1).where(range_end: higher+1)
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "TeachingRange"}).where(lesson_tags: {taggable: t.id})
    end

    @lessons = @lessons.page(@page)
    # Fetch subjects
    @filter_subjects = [] # TODO: turn subject param into array to check against

    # set difficulties
    @difficulty_helper = MasteryLevel.form_helper

    # Pagination stub, just so i can style the output - DH
    @paginatable_array = Kaminari.paginate_array([*1..280]).page(params[:page]).per(12)

  end

  def show
    @lesson_obj = Lesson.includes(:steps).find(params[:id])

    set_lesson_sections

    # Fetch any specified section and turn it into a sym, otherwise :overview
    @section = params[:section].present? ? params[:section].to_sym : :overview

  end

  def new

    # We only need to create a new empty lesson with an id here
    # before handing it off to edit. An id might have been provided already.
    # TODO: look up a lesson that in the middle of being created, by session id
    lesson = LessonService.find_or_create_and_update(params[:id], nil, current_user)
    lesson.steps << Step.new(summary: "")

    if lesson.present?
      redirect_to edit_lesson_path(lesson)
    else
      raise lesson.errors
    end

  end

  def edit

    # puts "edit here"
    # puts params.inspect

    @current_user = current_user

    # Assign the @form_step var, casting as integer instead of a string
    @form_step = params[:form_step].present? ? params[:form_step].to_i : 1
    @lesson_obj = Lesson.find(params[:id])

    #pundit --
    authorize @lesson_obj, :update?

    # If the form step is 2, i.e. standards, we redirect to create the first standard
    redirect_to new_lesson_standard_path(lesson_id: @lesson_obj.id, form_step: @form_step) if @form_step == 2

    # If the form step is 4, i.e. steps, we redirect to edit the first step created
    # when the lesson itself was created
    if @form_step == 4
      @steps = @lesson_obj.steps.order(:created_at).to_a
      unless @steps.present?
        @lesson_obj.steps << Step.new(summary: "")
        @lesson_obj.save!
        puts @lesson_obj.steps
        @steps = @lesson_obj.steps.to_a
      end
      @steps_array = @steps.map{|s| s.id}

      redirect_to edit_lesson_step_path(lesson_id: @lesson_obj.id, id: @lesson_obj.steps.first.id, form_step: @form_step)
    end

    if params[:lesson].present?
      @lesson_obj = LessonService.find_or_create_and_update(params[:id], lesson_params, @current_user)
    end
    files_hash = {}
    files_hash[:assessment_criteria_files] = params[:assessment_criteria_files] if params[:assessment_criteria_files].present?
    files_hash[:outcome_files] = params[:outcome_files] if params[:outcome_files].present?

    LessonService.add_file_by_type_to_id(@lesson_obj.id, files_hash) # should not be user first
    @lesson_obj.reload

    # elsif params[:id].present? && params[:step].present? # making a step
    #   Step.find_or_create_and_update(nil, params[:id], step_param, User.first).set_files(params)

    #@collections = CollectionTag.all.to_a.map{|x| x.name.titleize}
    @collections = CollectionTag.all
    @difficulty_helper = MasteryLevel.form_helper
    @teaching_range_helper = TeachingRange.inputRange

  end


  def update

    #raise params.to_yaml
    # puts lesson_params.inspect

    # Update the lesson
    @lesson_obj = LessonService.find_or_create_and_update(params[:id], lesson_params, User.first)

    # Redirect to the next step
    redirect_to edit_lesson_path(id: @lesson_obj.id, form_step: params[:form_step])

  end


  def upload_file
    @lesson = Lesson.find(params[:id])
     puts params.inspect
    #
    # # TODO - AUTHORIZE USER!!!!!
    # puts params[:files].inspect
    #  puts file_params.inspect
    #
    files = params[:files]
    files_hash = {}
    # puts "br"
    # puts files_hash
    files_hash[:assessment_criteria_files] = files if params[:attr] == "assessment_criteria_files"
    files_hash[:outcome_files] = files if params[:attr] == "outcome_files"
    returning = []

    # @lesson.addFiles( files_hash[:outcome_files][0], :outcome_files)

    if files_hash[:assessment_criteria_files].present?
      files_hash[:assessment_criteria_files].map{|k, v|
        @lesson.addFiles(v, :assessment_criteria)
      }
      @lesson.save!

      for i in 0..files_hash.count-1
        @lesson.reload
        x = @lesson.assessment_criteria_files[i]
        puts JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria")
        returning.append(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria"))
      end
    elsif files_hash[:outcome_files].present?
      puts "handing outcome files here\n\n\n\n\n"
      files_hash[:outcome_files].map{|k, v|
        @lesson.addFiles(v, :outcome)
      }
      @lesson.save!
      for i in 0..files_hash.count-1
        @lesson.reload
        x = @lesson.outcome_files[i]
        puts JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome")
        returning.append(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome"))
      end
    end


    respond_to do |format|
      format.html {
        render json: returning,
               content_type: "text/html",
               layout: false
      }
      format.json {
        render json: { files: returning }
      }
    end
  end

  def delete_file
    @lesson_obj = Lesson.find(params[:id])
    puts params.inspect
    file_name = params[:name]
    attribute = params[:attr]
    state = @lesson_obj.removeFileWithName(attribute.to_sym, file_name)
    # Return the attribute as json
    render json: {deleted: state}
  end

  def publish
    @lesson_obj = Lesson.find(params[:id])
    if @lesson_obj.publishable? &&  @lesson_obj.publish!
      redirect_to lesson_path_lesson_path(id: @lesson_obj.id), notice: 'Your lesson is published!'
    else
      redirect_to edit_lesson_path(id: @lesson_obj.id, form_step: 5), notice: 'Your lesson is not ready, check what\'s missing below!'
    end
  end

  def delete

    lesson = Lesson.find(params[:id])
    lesson.hidden!

    redirect_to lessons_path

  end



  def file_upload_load
    @lesson = Lesson.find(params[:id])
    returning = []
    if file_params[:attr] == "assessment_criteria_files"
        @lesson.assessment_criteria_files.map{|x|
          returning.push(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria"))
        }
    elsif
      file_params[:attr] == "outcome_files"
        @lesson.outcome_files.map{|x|
          returning.push(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome"))
        }
    end

    respond_to do |format|
      format.html {
        render json: returning.to_json,
               content_type: "text/html",
               layout: false
      }
      format.json {
        render json: { files: returning }, status: :created, location: @Uploaded
      }
    end
  end

  def remove_file_upload
    puts "prepping for delete"
    puts params.inspect
    @lesson = Lesson.find(params[:id])
    status = @lesson.removeFileWithName(remove_file_params[:attr].to_sym, remove_file_params[:name])
    puts "finished for delete"
    render json: {status: status}, location: @Uploaded
  end


  private

    def lesson_params
      params.require(:lesson).permit(:name, :topline, :summary, :tags, :teacher_notes, :assessment_criteria, :state, :collection_tag, :duration, :student_mastery, :educator_mastery, :teaching_range,other_users_emails: [], learning_objectives: [], further_readings: [], outcome_links: [], associated_places_ids: [], standards: [:name, descriptions: []], subjects: [], fabrication_tools: [], key_concepts: [], key_vocabularies: [], key_formulas: [], skills: [:name, :level], contexts: [])
    end

    def filter_params
      params.permit(lesson: [:name, :topline, :summary, :tags, :teacher_notes, :assessment_criteria, :state, :collection_tag, :duration, :student_mastery, :educator_mastery, :teaching_range,other_users_emails: [], learning_objectives: [], further_readings: [], outcome_links: [], associated_places_ids: [], standards: [:name, descriptions: []], subjects: [], fabrication_tools: [], key_concepts: [], key_vocabularies: [], key_formulas: [], skills: [:name, :level], contexts: []])
    end

    def step_params

app/helpers/lessons_helper.rb
module LessonsHelper
	
	def next_lesson_section(current_section = :overview)
		is_next = false
		@lesson_sections.each do |section, path|
			if is_next
				return path 
			end
			if section == current_section
				is_next = true
			end
		end
	end

	def prev_lesson_section(current_section = :overview)
		is_prev = false
		@lesson_sections.reverse_each do |section, path|
			if is_prev
				return path 
			end
			if section == current_section
				is_prev = true
			end
		end
	end

end

app/views/lessons/_edit_sub_nav.html.erb
<!-- sub navigation -->
<div class="SubNavigation">

  <div class="SubNavigation__content">

    <div class="SubNavigation__items">

      <%= active_link_to "Overview", edit_lesson_path(id: @lesson_obj.id, form_step:1),
        class: "SubNavigation__item SubNavigation__item--icon",
        class_active: "SubNavigation__item--icon--edit SubNavigation__item--active",
        class_inactive: @lesson_obj.publishable?(:overview) ? "SubNavigation__item--icon--completed" : "SubNavigation__item--icon--ellipsis",
        active: @form_step == 1 %>

      <%= active_link_to "Standards", edit_lesson_path(id: @lesson_obj.id, form_step:2),
        class: "SubNavigation__item SubNavigation__item--icon",
        class_active: "SubNavigation__item--icon--edit SubNavigation__item--active",
        class_inactive: @lesson_obj.publishable?(:standards) ? "SubNavigation__item--icon--completed" : "SubNavigation__item--icon--ellipsis",
        active: @form_step == 2 %>

      <%= active_link_to "Details", edit_lesson_path(id: @lesson_obj.id, form_step:3),
        class: "SubNavigation__item SubNavigation__item--icon",
        class_active: "SubNavigation__item--icon--edit SubNavigation__item--active",
        class_inactive: @lesson_obj.publishable?(:details) ? "SubNavigation__item--icon--completed" : "SubNavigation__item--icon--ellipsis",
        active: @form_step == 3 %>

      <%= active_link_to "Instructions", edit_lesson_path(id: @lesson_obj.id, form_step:4),
        class: "SubNavigation__item SubNavigation__item--icon",
        class_active: "SubNavigation__item--icon--edit SubNavigation__item--active",
        class_inactive: @lesson_obj.publishable?(:instructions) ? "SubNavigation__item--icon--completed" : "SubNavigation__item--icon--ellipsis",
        active: @form_step == 4 || @step_obj.present? %>

      <%= active_link_to "Outcomes", edit_lesson_path(id: @lesson_obj.id, form_step:5),
        class: "SubNavigation__item SubNavigation__item--icon",
        class_active: "SubNavigation__item--icon--edit SubNavigation__item--active",
        class_inactive: @lesson_obj.publishable?(:outcomes) ? "SubNavigation__item--icon--completed" : "SubNavigation__item--icon--ellipsis",
        active: @form_step == 5 %>

      <%= @form_step > 1 ? link_to(content_tag(:span, "Prev"), edit_lesson_path(id: @lesson_obj.id, form_step: @form_step - 1 ), class: "SubNavigation__nav SubNavigation__nav--prev") : nil %>
      <%= @form_step < 5 ? link_to(content_tag(:span, "Next"), edit_lesson_path(id: @lesson_obj.id, form_step: @form_step + 1 ), class: "SubNavigation__nav SubNavigation__nav--next") : nil %>

      <div class="SubNavigation__dots">
        <% (1..5).each do |i| %>
        <%= @form_step != i ? link_to("•", edit_lesson_path(id: @lesson_obj.id, form_step: i ), class: "SubNavigation__dot") : content_tag(:span, "•", class: "SubNavigation__dot") %>
        <% end %>
      </div>

    </div>

    <div class="SubNavigation__track <%= @lesson_obj.publishable? ? 'SubNavigation__track--publishable' : 'SubNavigation__track--locked' %>%">
      <div class="SubNavigation__status">
        <% if @lesson_obj.publishable? %>
          Well done, ready to publish!
        <% else %>
          Essential information missing
        <% end %>
      </div>
      <div class="Track">
        <div class='<%= "Track__progress Track__progress--#{@lesson_obj.publishable_count * 20}" %>'><span></span></div>
        <div class="Track__base"></div>
      </div>
    </div>

    <div class="SubNavigation__trackContent">

      <div class="SubNavigation__trackContent__header">
      
        <h5 class="SubNavigation__trackContent__heading">How to submit a lesson</h5>

        <p>Complete the following steps to be able to submit a great lesson.</p>

        <div class="SubNavigation__trackContent__completion">
          <span>
            <%= @lesson_obj.publishable_count %>
          </span> / 5 steps completed
        </div>

      </div>

      <div class="SubNavigation__trackContent__steps">
        <%= active_link_to "Add basic details", edit_lesson_path(id: @lesson_obj.id, form_step:1),
          class: "SubNavigation__trackContent__step",
          class_active: "SubNavigation__trackContent__step--completed",
          active: @lesson_obj.publishable?(:overview) %>

        <%= active_link_to "Add some standards", edit_lesson_path(id: @lesson_obj.id, form_step:2),
          class: "SubNavigation__trackContent__step",
          class_active: "SubNavigation__trackContent__step--completed",
          active: @lesson_obj.publishable?(:standards) %>

        <%= active_link_to "Add further details", edit_lesson_path(id: @lesson_obj.id, form_step:3),
          class: "SubNavigation__trackContent__step",
          class_active: "SubNavigation__trackContent__step--completed",
          active: @lesson_obj.publishable?(:details) %>

        <%= active_link_to "List the instructions", edit_lesson_path(id: @lesson_obj.id, form_step:4),
          class: "SubNavigation__trackContent__step",
          class_active: "SubNavigation__trackContent__step--completed",
          active: @lesson_obj.publishable?(:instructions) %>

        <%= active_link_to "Add the outcomes", edit_lesson_path(id: @lesson_obj.id, form_step:5),
          class: "SubNavigation__trackContent__step",
          class_active: "SubNavigation__trackContent__step--completed",
          active: @lesson_obj.publishable?(:outcomes) %>
      </div>

    </div>

  </div>

</div>

app/views/lessons/_filter_overlay.html.erb
<div class="FilterOverlay FilterOverlay--active">

  <button class="FilterOverlay__close"><span>✕</span></button>

  <div class="FilterOverlay__content">

    <%= form_tag(lessons_path, method: :get, class: "Form") do %>

      <%= field_set_tag nil, class: 'Form__fieldset' do %>

        <!-- collection -->
        <div class="FormField FormField--with-border">

          <div class="FormField__info">
            <label class="FormField__label" for="lesson_name">Collection</label>
          </div>

          <%= render partial: "lessons/form/collection" %>

        </div>

        <!-- subjects -->
        <div class="FormField FormField--with-border">

          <div class="FormField__info">
            <label class="FormField__label" for="lesson_name">Subjects</label>
          </div>

          <div class="FormField__input">
            <div class="CheckboxButtons">
              <% @subjects.each do |s| %>
              <div class="CheckboxButton">
                <input type="checkbox" class="CheckboxButton__input" name="lesson[subjects][]" value="<%= s.id %>" <%= @filter_subjects.include?(s) ? 'checked' : nil %> id="lesson__subjects__<%= s.id %>" />
                <label class="CheckboxButton__label Button Button--outline Button--small Button--extra-padding Button--icon Button--icon--<%= s.name %>" for="lesson__subjects__<%= s.id %>"><%= s.name.titleize %></label>
              </div>
              <% end %>
            </div>
          </div>

        </div>

        <!-- teaching_range -->
        <div class="FormField FormField--with-border">

          <div class="FormField__info">
            <label class="FormField__label" for="lesson_teaching_range">Teaching range</label>
          </div>

          <div class="FormField__input">
            <div class="Slider">
              <div class="Slider__value"></div>
              <div class="Slider__control" data-config="<%= { start: [3,5], connect: true, step: 1, range: { min: -1, max: 12 }, unit: 'ordinal' }.to_json %>">
                <input type="hidden" name="lesson[teaching_range]" value="<%= params[:teaching_range] %>" />
              </div>
            </div>
          </div>

        </div>

        <!-- difficulty -->
        <div class="FormField FormField--with-border">

          <div class="FormField__info">
            <label class="FormField__label" for="lesson_difficulty">Difficulty level</label>
          </div>

          <%= render partial: "lessons/form/mastery" %>

        </div>

        <!-- contexts -->
        <div class="FormField FormField--with-border">

          <div class="FormField__info">
            <label class="FormField__label" for="lesson_contexts">Contexts</label>
          </div>

          <%= render partial: "lessons/form/contexts" %>

        </div>

        <div class="Form__actions">
          <button type="submit" class="Button Button--primary Button--right Button--icon Button--icon--check">Apply filters</button>
        </div>

      <% end %>

    <% end %>

  </div>

</div>

app/views/lessons/_show_sub_nav.html.erb
<!-- sub navigation -->
<div class="SubNavigation">

  <div class="SubNavigation__content">

    <div class="SubNavigation__items">

      <%= active_link_to "Overview", lesson_path(id: @lesson_obj.id, section: :overview),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :overview %>

      <%= active_link_to "Standards", lesson_standards_path(lesson_id: @lesson_obj.id),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :standards %>

      <%= active_link_to "Steps", lesson_steps_path(lesson_id: @lesson_obj.id),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :steps %>

      <%= active_link_to "Outcomes", lesson_path(id: @lesson_obj.id, section: :outcomes),
        class: "SubNavigation__item",
        class_active: "SubNavigation__item--active",
        active: @section == :outcomes %>

      <%= prev_lesson_section(@section).present? ? link_to(content_tag(:span, "Prev"), prev_lesson_section(@section), class: "SubNavigation__nav SubNavigation__nav--prev") : nil %>
      <%= next_lesson_section(@section).present? ? link_to(content_tag(:span, "Next"), next_lesson_section(@section), class: "SubNavigation__nav SubNavigation__nav--next") : nil %>

      <div class="SubNavigation__dots">
        <% @lesson_sections.each do |name, path| %>
        <%= name != @section ? link_to("•", path, class: "SubNavigation__dot") : content_tag(:span, "•", class: "SubNavigation__dot") %>
        <% end %>
      </div>

    </div>

    <div class="SubNavigation__actions">
      <%= link_to "Edit Lesson", edit_lesson_path(id: @lesson_obj.id), class: "Button Button--small Button--icon Button--icon--edit" %>
    </div>

  </div>

</div>

app/views/lessons/_sub_header.html.erb
<div class="SubHeader">

  <div class="SubHeader__content">

    <h1 class="SubHeader__heading"><%= @lesson_obj.name.present? ? @lesson_obj.name : "New lesson" %></h1>

    <div class="SubHeader__tools">

      <%= active_link_to content_tag(:span, "Cancel"), delete_lesson_path(id: @lesson_obj.id), method: :delete, class: "SubHeader__tool SubHeader__tool--delete Button Button--small Button--light Button--outline Button--icon Button--icon--trash Button--no-label" %>

      <button class="SubHeader__tool SubHeader__tool--draft Button Button--small Button--icon Button--icon--document Button--outline Button--light">Save as Draft</button>

      <!-- TODO: Button--disabled class is dependent on @lesson_obj.publishable? function working, erroring right now -->
      <%= active_link_to "Publish Lessson", publish_lesson_path(id: @lesson_obj.id), method: :put, class: "SubHeader__tool SubHeader__tool--publish Button Button--small Button--icon #{@lesson_obj.publishable? ? "Button--icon--check" : "Button--icon--locked Button--disabled"}" %>



    </div>

  </div>

</div>

app/views/lessons/_thumb.html.erb
<div class="Thumb">

  <%= link_to lesson_path(lesson), class: "Thumb__image" do %>
    <% if lesson.outcome_files.present? %>
    <img src="<%= lesson.outcome_files.first.url(:thumbnail) %>" srcset="<%= lesson.outcome_files.first.url(:thumbnail) %> 1x, <%= lesson.outcome_files.first.url(:thumbnail2x) %> 2x" class="Image Image--lazy" />
    <% end %>
  <% end %>

  <div class="Thumb__content">

    <%= link_to lesson.name, lesson_path(lesson), class: "Thumb__title" %>

    <div class="Thumb__description">
      <%= lesson.topline %>
    </div>

  </div>

  <div class="Thumb__footer">
    <%= render partial: "components/user_badge", locals: { size: :small, author: lesson.authors.first } %>
  </div>

</div>

app/views/lessons/edit.html.erb
<%= render partial: 'lessons/sub_header' %>

<%= render partial: 'lessons/edit_sub_nav' %>

<%= render partial: "lessons/edit/step#{@form_step}" %>

app/views/lessons/new.html.erb
<div class="SubHeader">

  <div class="SubHeader__content">

    <h1 class="SubHeader__heading"><%= @lesson_obj.name.present? ? @lesson_obj.name : "New lesson" %></h1>

    <div class="SubHeader__tools">
      <%= active_link_to "<span>Cancel</span>".html_safe, lesson_delete_path(id: @lesson_obj.id), class: "SubHeader__tool Button Button--small Button--light Button--outline Button--icon Button--icon--trash Button--no-label" %>
      <%= active_link_to "Save as Draft", '#', class: "SubHeader__tool Button Button--small Button--light Button--icon Button--icon--document Button--outline Button--icon-document" %>
      <%= active_link_to "Publish Lessson", lesson_publish_path(id: @lesson_obj.id), class: "SubHeader__tool Button Button--small Button--icon Button--icon Button--icon--locked Button--dark Button--disabled" %>
    </div>

  </div>

</div>

<!-- sub navigation -->
<div class="SubNavigation">

  <div class="SubNavigation__content">

    <div class="SubNavigation__items">
      <%= active_link_to "Overview", lesson_new_path(id: @lesson_obj.id, form_step:1), class: "SubNavigation__item", class_active: "SubNavigation__item--active", active: @form_step == 1 %>
      <%= active_link_to "Standards", lesson_new_path(id: @lesson_obj.id, form_step:2), class: "SubNavigation__item", class_active: "SubNavigation__item--active", active: @form_step == 2 %>
      <%= active_link_to "Details", lesson_new_path(id: @lesson_obj.id, form_step:3), class: "SubNavigation__item", class_active: "SubNavigation__item--active", active: @form_step == 3 %>
      <%= active_link_to "Instructions", lesson_new_path(id: @lesson_obj.id, form_step:4), class: "SubNavigation__item", class_active: "SubNavigation__item--active", active: @form_step == 4 %>
      <%= active_link_to "Outcomes", lesson_new_path(id: @lesson_obj.id, form_step:5), class: "SubNavigation__item", class_active: "SubNavigation__item--active", active: @form_step == 5 %>
    </div>

    <div class="SubNavigation__track">
      <div class="SubNavigation__status">
        Essential information missing
      </div>
      <div class="Track">
        <div class="Track__progress"><span>10%</span></div>
        <div class="Track__base"></div>
      </div>
    </div>

  </div>

</div>

<%= render partial: "lessons/new/step#{@form_step}" %>