config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'
  } # CSRF_forgery makes this fail :3

  resources :users

  # -- Lessons

  resources :lessons do
    member do
      delete :delete
      put :publish
      post :upload_file, as: :upload_file_for
      post :delete_file, as: :delete_file_for
      get 'show' => 'lessons#show', as: 'lesson_path' # a dummy route to show dummy lesson
    end
    resources :steps do
      post :upload_file, as: :upload_file
      post :delete_file, as: :delete_file
    end
    resources :standards
  end

  resources :people
  resources :places

  get 'search' => 'search#index'


  #get  'lessons/new' => 'lessons#new', as: :lesson_new
  # post 'lessons'            => 'lessons#create'#, as: :lesson_create
  #post 'lessons/new'            => 'lessons#new', as: :lesson_create
  # the above line is strictly used for the weekend of the 13/7/2017 for submit on new page loads

  #get 'lessons/test'  => 'lessons#test', as: :lesson_test

  #post '/lessons/:id/publish' => 'lessons#publis', as: :lesson_publish#--
  #put  'lessons/:id'        => 'lessons#update'
  #delete 'lessons/:id' => 'lessons#delete', as: :lesson_delete #--

  #post 'lessons/:id/step'   => 'lessons#add_step'

  #delete 'lessons/:id/step/:step_id'   => 'lessons#delete_step'

  #get 'lessons/:id/file/:attr', to: 'lessons#file_upload_load', as: :lesson_file_data
  #post 'lessons/:id/file/:attr', to: 'lessons#file_upload', as: :lesson_file
  #delete 'lessons/:id/file', to: 'lessons#remove_file_upload', as: :delete_lesson_file
  #~~~~~~~~~~

  #get 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload_load', as: :lesson_step_file_data
  #post 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload', as: :step_file
  #delete 'lessons/:id/:step/file', to: 'lessons#step_remove_file_upload', as: :delete_step_file

  #get 'lessons/:id'        => 'lessons_public#show', as: :lesson_view
  #get 'list/lessons'  => 'lessons_public#list', as: :lesson_list

  #~~~~ Steps Ajax
  #put     'lessons/:id/steps' => 'lessons#set_steps'
  #delete  'lessons/:id/steps' => 'lessons#remove_step'
  #~~~~~~~~~~

  # -- .Lessons

  get 'file_form'         => 'visitors#form'
  post 'file_upload'      => 'visitors#file_form_upload',  as: :lesson_file_test

  post 'register' => 'visitors#register_interest', as: :register

  post 'users/affiliate' => 'users#affiliate_organization_id'

  get 'api/users/exists'   =>  'secured_api#user_presence'

  #get 'search/:entity', :to => 'search#main', as: :search

  # Static pages
  get 'enter' =>  'visitors#enter', as: :enter
  get 'about' => 'visitors#about', as: :about
  get 'policy' => 'visitors#policy', as: :policy
  get 'get_involved' => 'visitors#get_involved', as: :involved

end

app/controllers/lessons_controller.rb
# frozen_string_literal: true
class LessonsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :update, :delete_file, :upload_file, :publish]
  #skip_before_action :verify_authenticity_token

  before_action :set_lesson, only: [:show, :activity]
  before_action :set_contexts, only: [:index, :edit]
  before_action :set_subjects, only: [:index, :edit]
  before_action :set_collections, only: [:index, :edit]
  before_action :set_fabrication_tools, only: [:index, :edit]

  def index
    # Using lessons#index for now as the public view of all lesson
    # No authentication heres

    # Fetch the page number, otherwise 1
    @page = params[:page] || 1

    param = filter_params[:lesson]


    @lessons = Lesson.includes(:steps).visible

    @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "CollectionTag"}).where(lesson_tags: {taggable: param[:collection_tag]}) if param[:collection_tag].present?

    param[:subjects].map{|x|
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "Subject"}).where(lesson_tags: {taggable: x})
    } if param[:subjects].present?

    param[:contexts].map{|x|
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "Subject"}).where(lesson_tags: {taggable: x})
    } if param[:contexts].present?

    if param[:teaching_range].present?
      lower = param[:teaching_range][:start]
      higher = param[:teaching_range][:end]
      t = TeachingRange.where(range_start: lower+1).where(range_end: higher+1)
      @lessons = @lessons.joins(:lesson_tags).where(lesson_tags: {taggable_type: "TeachingRange"}).where(lesson_tags: {taggable: t.id})
    end

    @lessons = @lessons.page(@page)
    # Fetch subjects
    @filter_subjects = [] # TODO: turn subject param into array to check against

    # set difficulties
    @difficulty_helper = MasteryLevel.form_helper

    # Pagination stub, just so i can style the output - DH
    @paginatable_array = Kaminari.paginate_array([*1..280]).page(params[:page]).per(12)

  end

  def show
    @lesson_obj = Lesson.includes(:steps).find(params[:id])

    set_lesson_sections

    # Fetch any specified section and turn it into a sym, otherwise :overview
    @section = params[:section].present? ? params[:section].to_sym : :overview

  end

  def new

    # We only need to create a new empty lesson with an id here
    # before handing it off to edit. An id might have been provided already.
    # TODO: look up a lesson that in the middle of being created, by session id
    lesson = LessonService.find_or_create_and_update(params[:id], nil, current_user)
    lesson.steps << Step.new(summary: "")

    if lesson.present?
      redirect_to edit_lesson_path(lesson)
    else
      raise lesson.errors
    end

  end

  def edit

    # puts "edit here"
    # puts params.inspect

    @current_user = current_user

    # Assign the @form_step var, casting as integer instead of a string
    @form_step = params[:form_step].present? ? params[:form_step].to_i : 1
    @lesson_obj = Lesson.find(params[:id])

    #pundit --
    authorize @lesson_obj, :update?

    # If the form step is 2, i.e. standards, we redirect to create the first standard
    redirect_to new_lesson_standard_path(lesson_id: @lesson_obj.id, form_step: @form_step) if @form_step == 2

    # If the form step is 4, i.e. steps, we redirect to edit the first step created
    # when the lesson itself was created
    if @form_step == 4
      @steps = @lesson_obj.steps.order(:created_at).to_a
      unless @steps.present?
        @lesson_obj.steps << Step.new(summary: "")
        @lesson_obj.save!
        puts @lesson_obj.steps
        @steps = @lesson_obj.steps.to_a
      end
      @steps_array = @steps.map{|s| s.id}

      redirect_to edit_lesson_step_path(lesson_id: @lesson_obj.id, id: @lesson_obj.steps.first.id, form_step: @form_step)
    end

    if params[:lesson].present?
      @lesson_obj = LessonService.find_or_create_and_update(params[:id], lesson_params, @current_user)
    end
    files_hash = {}
    files_hash[:assessment_criteria_files] = params[:assessment_criteria_files] if params[:assessment_criteria_files].present?
    files_hash[:outcome_files] = params[:outcome_files] if params[:outcome_files].present?

    LessonService.add_file_by_type_to_id(@lesson_obj.id, files_hash) # should not be user first
    @lesson_obj.reload

    # elsif params[:id].present? && params[:step].present? # making a step
    #   Step.find_or_create_and_update(nil, params[:id], step_param, User.first).set_files(params)

    #@collections = CollectionTag.all.to_a.map{|x| x.name.titleize}
    @collections = CollectionTag.all
    @difficulty_helper = MasteryLevel.form_helper
    @teaching_range_helper = TeachingRange.inputRange

  end


  def update

    #raise params.to_yaml
    # puts lesson_params.inspect

    # Update the lesson
    @lesson_obj = LessonService.find_or_create_and_update(params[:id], lesson_params, User.first)

    # Redirect to the next step
    redirect_to edit_lesson_path(id: @lesson_obj.id, form_step: params[:form_step])

  end


  def upload_file
    @lesson = Lesson.find(params[:id])
     puts params.inspect
    #
    # # TODO - AUTHORIZE USER!!!!!
    # puts params[:files].inspect
    #  puts file_params.inspect
    #
    files = params[:files]
    files_hash = {}
    # puts "br"
    # puts files_hash
    files_hash[:assessment_criteria_files] = files if params[:attr] == "assessment_criteria_files"
    files_hash[:outcome_files] = files if params[:attr] == "outcome_files"
    returning = []

    # @lesson.addFiles( files_hash[:outcome_files][0], :outcome_files)

    if files_hash[:assessment_criteria_files].present?
      files_hash[:assessment_criteria_files].map{|k, v|
        @lesson.addFiles(v, :assessment_criteria)
      }
      @lesson.save!

      for i in 0..files_hash.count-1
        @lesson.reload
        x = @lesson.assessment_criteria_files[i]
        puts JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria")
        returning.append(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria"))
      end
    elsif files_hash[:outcome_files].present?
      puts "handing outcome files here\n\n\n\n\n"
      files_hash[:outcome_files].map{|k, v|
        @lesson.addFiles(v, :outcome)
      }
      @lesson.save!
      for i in 0..files_hash.count-1
        @lesson.reload
        x = @lesson.outcome_files[i]
        puts JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome")
        returning.append(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome"))
      end
    end


    respond_to do |format|
      format.html {
        render json: returning,
               content_type: "text/html",
               layout: false
      }
      format.json {
        render json: { files: returning }
      }
    end
  end

  def delete_file
    @lesson_obj = Lesson.find(params[:id])
    puts params.inspect
    file_name = params[:name]
    attribute = params[:attr]
    state = @lesson_obj.removeFileWithName(attribute.to_sym, file_name)
    # Return the attribute as json
    render json: {deleted: state}
  end

  def publish
    @lesson_obj = Lesson.find(params[:id])
    if @lesson_obj.publishable? &&  @lesson_obj.publish!
      redirect_to lesson_path_lesson_path(id: @lesson_obj.id), notice: 'Your lesson is published!'
    else
      redirect_to edit_lesson_path(id: @lesson_obj.id, form_step: 5), notice: 'Your lesson is not ready, check what\'s missing below!'
    end
  end

  def delete

    lesson = Lesson.find(params[:id])
    lesson.hidden!

    redirect_to lessons_path

  end



  def file_upload_load
    @lesson = Lesson.find(params[:id])
    returning = []
    if file_params[:attr] == "assessment_criteria_files"
        @lesson.assessment_criteria_files.map{|x|
          returning.push(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "assessment_criteria"))
        }
    elsif
      file_params[:attr] == "outcome_files"
        @lesson.outcome_files.map{|x|
          returning.push(JqUploaderService.convert_to_jq_upload(x, @lesson.id, "outcome"))
        }
    end

    respond_to do |format|
      format.html {
        render json: returning.to_json,
               content_type: "text/html",
               layout: false
      }
      format.json {
        render json: { files: returning }, status: :created, location: @Uploaded
      }
    end
  end

  def remove_file_upload
    puts "prepping for delete"
    puts params.inspect
    @lesson = Lesson.find(params[:id])
    status = @lesson.removeFileWithName(remove_file_params[:attr].to_sym, remove_file_params[:name])
    puts "finished for delete"
    render json: {status: status}, location: @Uploaded
  end


  private

    def lesson_params
      params.require(:lesson).permit(:name, :topline, :summary, :tags, :teacher_notes, :assessment_criteria, :state, :collection_tag, :duration, :student_mastery, :educator_mastery, :teaching_range,other_users_emails: [], learning_objectives: [], further_readings: [], outcome_links: [], associated_places_ids: [], standards: [:name, descriptions: []], subjects: [], fabrication_tools: [], key_concepts: [], key_vocabularies: [], key_formulas: [], skills: [:name, :level], contexts: [])
    end

    def filter_params
      params.permit(lesson: [:name, :topline, :summary, :tags, :teacher_notes, :assessment_criteria, :state, :collection_tag, :duration, :student_mastery, :educator_mastery, :teaching_range,other_users_emails: [], learning_objectives: [], further_readings: [], outcome_links: [], associated_places_ids: [], standards: [:name, descriptions: []], subjects: [], fabrication_tools: [], key_concepts: [], key_vocabularies: [], key_formulas: [], skills: [:name, :level], contexts: []])
    end

    def step_params

app/helpers/lessons_helper.rb
module LessonsHelper
	
	def next_lesson_section(current_section = :overview)
		is_next = false
		@lesson_sections.each do |section, path|
			if is_next
				return path 
			end
			if section == current_section
				is_next = true
			end
		end
	end

	def prev_lesson_section(current_section = :overview)
		is_prev = false
		@lesson_sections.reverse_each do |section, path|
			if is_prev
				return path 
			end
			if section == current_section
				is_prev = true
			end
		end
	end

end

app/views/lessons/edit/_step1.html.erb
<%= form_tag(lesson_path(id: @lesson_obj.id, form_step:2), method: :patch, multipart: true, class: "Form") do %>

  <%= field_set_tag 'Basic Information', class: 'Form__fieldset Form__fieldset--with-border' do %>

    <!-- lesson.name -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_name">Lesson Title</label>
        <div class="FormField__hint">50 chars max</div>
      </div>

      <div class="FormField__input">
        <input type="text" name="lesson[name]" class="Input Input--large" value="<%= @lesson_obj.name %>" id="lesson_name" maxlength="50" required
          placeholder="Name your lesson" />
      </div>

    </div>

    <!-- lesson.topline -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_topline">Quick Pitch</label>
        <div class="FormField__hint">Describe the learning in one sentence, 140 chars max</div>
      </div>

      <div class="FormField__input">
        <input type="text" name="lesson[topline]" class="Input" value="<%= @lesson_obj.topline %>" id="lesson_topline" maxlength="140" required
          placeholder="How would you describe it in one sentence?" />
      </div>

    </div>

    <!-- lesson.summary -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_summary">Summary</label>
        <div class="FormField__hint">
          <p>Keep it short and snappy</p>
          <p>Try to include:</p>
          <ul>
            <li>Why the lesson is interesting</li>
            <li>The types of activities students will do.</li>
          </ul>
          <p>You can format using [Markdown]() markup language.</p>
        </div>
      </div>

      <div class="FormField__input">
        <textarea class="Input Input--textarea Input--autosize Input--character-count" rows="5" maxlength="800" name="lesson[summary]" id="lesson_summary" required><%= @lesson_obj.summary %></textarea>
      </div>

    </div>

  <% end %>

  <%= field_set_tag 'Objectives', class: 'Form__fieldset Form__fieldset--with-border' do %>

    <!-- lesson.learning_objectives -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_topline">Learning Objectives</label>
        <div class="FormField__hint">What will the students learn</div>
      </div>

      <div class="FormField__input FormField__input--multiple">
        <input type="text" name="lesson[learning_objectives][]" class="Input Input--multiple" data-values='<%= @lesson_obj.learning_objectives.to_json %>' value="" placeholder="+ Add a new objective" id="lesson_objectives_1" required />
      </div>

    </div>

  <% end %>

  <%= field_set_tag nil, class: 'Form__fieldset Form__fieldset--with-border' do %>

    <!-- lesson.teacher_notes -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_teacher_notes">Teacher Notes</label>
      </div>

      <div class="FormField__input">
        <textarea class="Input Input--textarea Input--autosize" rows="5" name="lesson[teacher_notes]" id="lesson_teacher_notes" required><%= @lesson_obj.teacher_notes %></textarea>
      </div>

    </div>

    <!-- lesson.assessment_criteria -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="assessment_criteria">Assessment</label>
        <div class="FormField__hint">
          <p>Briefly describe how you assessed student learning in this lesson</p>
        </div>
      </div>

      <div class="FormField__input">
        <textarea class="Input Input--textarea Input--autosize Input--character-count" rows="5" maxlength="800" name="lesson[assessment_criteria]" id="lesson_assessment_criteria" placeholder="How are the students assessed? Feel free to attach files and more" required><%= @lesson_obj.assessment_criteria %></textarea>
      </div>

    </div>

    <!-- lesson.assessment_criteria_files -->
    <div class="FormField">

      <div class="FormField__info">
        <label class="FormField__label" for="assessment_criteria_files">Supporting Files</label>
        <div class="FormField__hint">
          <p>Supporting documentation for the whole lesson</p>
        </div>
      </div>

      <div class="FormField__input">
        <div class="dropzone" data-url="<%= upload_file_for_lesson_path(@lesson_obj.id, attr: :assessment_criteria_files) %>" id="assessment_criteria_files">
        </div>

        <div class="FormUploads">
          <% @lesson_obj.assessment_criteria_files.each do |file| %>
            <div class="FormUploads__file FormUploads__file--<%= file.file.extension %>">
              <%= link_to file.file.filename, file.url, class: "FormUploads__link" %>
              <%= link_to "✕", delete_file_for_lesson_path(@lesson_obj.id, attr: :assessment_criteria_files, name: file.file.filename), class: "FormUploads__delete" %>
            </div>
          <% end %>
        </div>

      </div>

    </div>

  <% end %>

  <%= field_set_tag nil, class: 'Form__fieldset' do %>

    <!-- lesson.further_readings -->
    <div class="FormField">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_further_readings_1">Further Reading</label>
        <div class="FormField__hint">Notes and links to additional reading and research</div>
      </div>

      <div class="FormField__input FormField__input--multiple">
        <input type="url" data-parsley-type="url" name="lesson[further_readings][]" class="Input Input--multiple" data-values='<%= @lesson_obj.further_readings.to_json %>' 
          value="" placeholder="+ Add a new URL" id="lesson_further_readings_1" />
      </div>

    </div>

  <% end %>

  <div class="Form__footer">

    <div class="Form__footer__content">

      <div class="Form__footer__heading">
        Next up... <span>Tell us more how the lesson aligns to standards...</span>
      </div>

      <div class="Form__footer__actions Form__footer__actions--right">
        <button class="Form__footer__action Button Button--primary Button--small Button--icon Button--icon--right Button--arrow--right">Add some Standards</button>
      </div>

    </div>

  </div>

<% end %>

app/views/lessons/edit/_step2.html.erb
<!-- standards/_form !>

app/views/lessons/edit/_step3.html.erb
<%= form_tag(lesson_path(id: @lesson_obj.id, form_step:4), method: :patch, multipart: true, class: "Form") do %>

  <%= field_set_tag 'Who is this for?', class: 'Form__fieldset' do %>

    <!-- lesson.teaching_range -->
    <div class="FormField FormField--required FormField--with-border">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_teaching_range">Teaching Range</label>
        <div class="FormField__hint">Choose a teaching range (U.S.)</div>
      </div>

      <%= render partial: 'lessons/form/teaching_range' %>

    </div>

    <!-- lesson.contexts -->
    <div class="FormField FormField--with-border">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_contexts">Context</label>
        <div class="FormField__hint">Where was this lesson first tested?</div>
      </div>

      <%= render partial: "lessons/form/contexts" %>

    </div>

    <!-- lesson.subjects -->
    <div class="FormField FormField--required FormField--with-border">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_subjects">Subjects</label>
        <div class="FormField__hint">Choose one or more Subjects explored</div>
      </div>

      <%= render partial: "lessons/form/subjects" %>

    </div>

    <!-- lesson.mastery -->
    <div class="FormField FormField--with-border">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_mastery">Mastery Level</label>
        <div class="FormField__hint">What is student and educator pre-requisite mastery or experience level?</div>
      </div>

      <%= render partial: "lessons/form/mastery" %>

    </div>

  <% end %>

  <%= field_set_tag 'What will we learn?', class: 'Form__fieldset' do %>

    <!-- lesson.fabrication_tools -->
    <div class="FormField FormField--required FormField--with-padding">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_fabrication_tools">Digital Fabrication</label>
        <div class="FormField__hint">Which digital fabrication tools are explored in this lesson?</div>
      </div>

      <%= render partial: "lessons/form/fabrication_tools" %>

    </div>

    <!-- lesson.duration -->
    <div class="FormField FormField--required FormField--with-padding">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_duration">Total Lesson Time</label>
      </div>

      <div class="FormField__input">
        <input type="text" name="lesson[duration]" class="Input" value="<%= @lesson_obj.duration %>" placeholder="Approximately" id="lesson_duration" required />
      </div>

    </div>

    <!-- lesson.key_concepts -->
    <div class="FormField FormField--required FormField--with-padding">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_key_concepts_1">Key Concepts</label>
        <div class="FormField__hint">Add one or more</div>
      </div>

      <div class="FormField__input FormField__input--multiple">
        <input type="text" name="lesson[key_concepts][]" class="Input Input--multiple" data-values='<%= @lesson_obj.key_concepts.to_json %>' value="" placeholder="+ Add a new concept" id="lesson_key_concepts_1" required />
      </div>

    </div>

    <!-- lesson.key_vocabularies -->
    <div class="FormField FormField--required FormField--with-padding">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_key_concepts_1">Key Vocabularies</label>
        <div class="FormField__hint">Add one or more</div>
      </div>

      <div class="FormField__input FormField__input--multiple">
        <input type="text" name="lesson[key_vocabularies][]" class="Input Input--multiple" data-values='<%= @lesson_obj.key_vocabularies.to_json %>' value="" placeholder="+ Add a new vocabulary" id="lesson_key_vocabularies_1" required />
      </div>

    </div>

    <!-- lesson.key_formulas -->
    <div class="FormField FormField--required FormField--with-padding">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_key_concepts_1">Key Formulas</label>
        <div class="FormField__hint">Add one or more</div>
      </div>

      <div class="FormField__input FormField__input--multiple">
        <input type="text" name="lesson[key_formulas][]" class="Input Input--multiple" data-values='<%= @lesson_obj.key_formulas.to_json %>' value="" placeholder="+ Add a new formula" id="lesson_key_formulas_1" required />
      </div>

    </div>

    <!-- lesson.collection -->
    <div class="FormField FormField--with-border">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_collection_tag">Collection</label>
        <div class="FormField__hint">Does this belong to a collection?</div>
      </div>

      <%= render partial: "lessons/form/collection" %>

    </div>

    <!-- lesson.tags -->
    <div class="FormField FormField--required">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_name">Tags</label>
        <div class="FormField__hint">Enter comma separated tags, to further identify or categorize the learning</div>
      </div>

      <div class="FormField__input">
        <input type="text" class="Input--choices" autocomplete="off" autocapitalize="off" spellcheck="false" role="textbox" aria-autocomplete="list" placeholder="Enter a tag..." data-items="" name="lesson[tags]" value="<%= @lesson_obj.tags.join(', ') %>" required>
      </div>

    </div>

  <% end %>

  <div class="Form__footer">

    <div class="Form__footer__content">

      <div class="Form__footer__actions">
        <a href="#" class="Form__footer__action Button Button--primary Button--small Button--icon Button--icon--left Button--arrow--left">Back to Standards</a>
        <button class="Form__footer__action Button Button--primary Button--small Button--icon Button--icon--right Button--arrow--right">Add some Instructions</button>
      </div>

    </div>

  </div>


<% end %>

app/views/lessons/edit/_step4.html.erb
<!-- steps/_form !>

app/views/lessons/edit/_step5.html.erb
<%= form_tag(lesson_path(id: @lesson_obj.id, form_step:5), method: :patch, multipart: true, class: "Form") do %>

  <%= field_set_tag 'Examples of finished work', class: 'Form__fieldset' do %>

    <!-- lesson.outcome_files -->
    <div class="FormField">

      <div class="FormField__info">
        <label class="FormField__label" for="lesson_outcome_files">Add images</label>
        <div class="FormField__hint">
          <p>Image specifications here</p>
        </div>
      </div>

      <div class="FormField__input">
        <div class="dropzone" data-url="<%= upload_file_for_lesson_path(@lesson_obj.id, attr: :outcome_files) %>" id="outcome_files">
        </div>

        <div class="FormUploads">
          <% @lesson_obj.outcome_files.each do |file| %>
            <div class="FormUploads__file FormUploads__file--<%= file.file.extension %>">
              <%= link_to file.file.filename, file.url, class: "FormUploads__link" %>
              <%= link_to "✕", delete_file_for_lesson_path(@lesson_obj.id, attr: :outcome_files, name: file.file.filename), class: "FormUploads__delete" %>
            </div>
          <% end %>
        </div>

      </div>

    </div>

  <% end %>

  <div class="Form__footer">

    <div class="Form__footer__content">

      <div class="Form__footer__actions">
        <%= link_to "Back to Instructions", edit_lesson_path(id: @lesson_obj.id, form_step: 4), class: 'Form__footer__action Button Button--primary Button--small Button--icon Button--icon--left Button--arrow--left' %>

        <%= link_to "Publish Lesson", publish_lesson_path(id: @lesson_obj.id), method: :put, class: "Form__footer__action Button Button--primary Button--small Button--icon #{@lesson_obj.publishable? ? "Button--icon--check" : "Button--icon--locked Button--disabled"}" %>
        <!--<button class="Form__footer__action Button Button&#45;&#45;primary Button&#45;&#45;small Button&#45;&#45;icon Button&#45;&#45;icon&#45;&#45;check">Publish Lesson</button>-->
      </div>

    </div>

  </div>

<% end %>