config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :users, controllers: {
    sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'
  } # CSRF_forgery makes this fail :3

  resources :users

  # -- Lessons

  resources :lessons do
    member do
      delete :delete
      put :publish
      post :upload_file, as: :upload_file_for
      post :delete_file, as: :delete_file_for
      get 'show' => 'lessons#show', as: 'lesson_path' # a dummy route to show dummy lesson
    end
    resources :steps do
      post :upload_file, as: :upload_file
      post :delete_file, as: :delete_file
    end
    resources :standards
  end

  resources :people
  resources :places

  get 'search' => 'search#index'


  #get  'lessons/new' => 'lessons#new', as: :lesson_new
  # post 'lessons'            => 'lessons#create'#, as: :lesson_create
  #post 'lessons/new'            => 'lessons#new', as: :lesson_create
  # the above line is strictly used for the weekend of the 13/7/2017 for submit on new page loads

  #get 'lessons/test'  => 'lessons#test', as: :lesson_test

  #post '/lessons/:id/publish' => 'lessons#publis', as: :lesson_publish#--
  #put  'lessons/:id'        => 'lessons#update'
  #delete 'lessons/:id' => 'lessons#delete', as: :lesson_delete #--

  #post 'lessons/:id/step'   => 'lessons#add_step'

  #delete 'lessons/:id/step/:step_id'   => 'lessons#delete_step'

  #get 'lessons/:id/file/:attr', to: 'lessons#file_upload_load', as: :lesson_file_data
  #post 'lessons/:id/file/:attr', to: 'lessons#file_upload', as: :lesson_file
  #delete 'lessons/:id/file', to: 'lessons#remove_file_upload', as: :delete_lesson_file
  #~~~~~~~~~~

  #get 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload_load', as: :lesson_step_file_data
  #post 'lessons/:id/:step/file/:attr', to: 'lessons#step_file_upload', as: :step_file
  #delete 'lessons/:id/:step/file', to: 'lessons#step_remove_file_upload', as: :delete_step_file

  #get 'lessons/:id'        => 'lessons_public#show', as: :lesson_view
  #get 'list/lessons'  => 'lessons_public#list', as: :lesson_list

  #~~~~ Steps Ajax
  #put     'lessons/:id/steps' => 'lessons#set_steps'
  #delete  'lessons/:id/steps' => 'lessons#remove_step'
  #~~~~~~~~~~

  # -- .Lessons

  get 'file_form'         => 'visitors#form'
  post 'file_upload'      => 'visitors#file_form_upload',  as: :lesson_file_test

  post 'register' => 'visitors#register_interest', as: :register

  post 'users/affiliate' => 'users#affiliate_organization_id'

  get 'api/users/exists'   =>  'secured_api#user_presence'

  #get 'search/:entity', :to => 'search#main', as: :search

  # Static pages
  get 'enter' =>  'visitors#enter', as: :enter
  get 'about' => 'visitors#about', as: :about
  get 'policy' => 'visitors#policy', as: :policy
  get 'get_involved' => 'visitors#get_involved', as: :involved

end

app/models/standard.rb
# == Schema Information
#
# Table name: standards
#
#  id           :uuid             not null, primary key
#  name         :string           not null
#  autocomplete :string           default([]), is an Array
#

class Standard < ApplicationRecord
  
  has_many :lessons_standards
  has_many :lessons, through: :lessons_standards

  validates_uniqueness_of :name

  def self.seed
    self.seed_values.map{|x|
      begin
        new(name: x[:name], autocomplete: x[:autocomplete]).save!
      rescue ActiveRecord::RecordInvalid => e
        next
      end
    }
  end

  def self.name_array
    Standard.all.to_a.map{|x| x.name}.uniq
  end

  def to_s
    name
  end

  private
  def self.seed_values # TODO -- FINISH ADDING THIS!
    [
        {name: "NGSS"},
        {name: "Common Core ELA"},
        {name: "Common Core Math"},
        {name: "FAB I Can Statements"},
        {name: "21st Century Skills"},
        {name: "Other"},

        # I CAN BELOW

        {name: "I Can - Safety", autocomplete: ["Novice - I can safely conduct myself in a Fab Lab, observe operations and follow general safety protocols under guidance from an instructor.","Intermediate - I can operate equipment in a Fab Lab following safety protocols.", "Advanced - I can supervise others in a Fab Lab and ensure safety protocols are being followed."]},


        {name: "I Can - Design Process", autocomplete: ["Novice - I can modify an existing design under instructor guidance.", "Novice - I can design something in a Fab Lab using a specific process under close instructor guidance.", "Novice - I can create analog models (e.g. sketches, small physical models, etc.) to facilitate a design process.", "Novice - I can record and share my ideas during a design process to document the learning process (e.g. journal writing, group reviews, etc.)", "Intermediate - I can work with a group to follow multiple common design process steps (e.g. defining the user, brainstorming, prototyping, iterating, etc.).", "Advanced - I can use a specified process multiple times to design, iterate and fabricate an item with limited instructor intervention.", "Advanced - I can guide others through a design process in a Fab Lab."]},


        {name: "I Can - Computer Assisted Design", autocomplete: ["Novice - I can draw a basic design using 2D Vector graphics.", "Novice - I can draw a basic design using 2D Raster Graphics.", "Intermediate - I can draw a basic design using any 3D CAD software.", "Intermediate - I can design a part to be fabricated in 2D with dimensional precision and with fabrication tolerances. ", "Advanced - I can design a 2D press-fit part.", "Advanced - I can design a 3D component using 2D design software (e.g. press-fit or folded components).", "Advanced - I can design a part to be fabricated in 3D with dimensional precision and with fabrication tolerances within 3D software.", "Advanced - I can use CAD software to produce multiple drawings of the same part from various projections to depict all of its features."]},


        {name: "I Can - Machine Operation", autocomplete: ["Novice - I can safely observe a digital fabrication machine working and describe their operation.", "Intermediate - I can safely operate a digital fabrication machine under close observation of an instructor.", "Advanced - I can safely operate a digital fabrication machine independently or in small groups.", "Advanced - I can train others to safely operate a digital fabrication machine."]},


        {name: "I Can - Fabrication", autocomplete: ["Novice - I can assemble an object using prefabricated components.", "Novice - I can fabricate pre-designed components using one digital fabrication process under instructor guidance.", "Intermediate - I can modify pre-designed components and subsequently fabricate the components using one digital fabrication process.", "Intermediate - I can fabricate components of my own design using a single digital fabrication process.", "Advanced - I can fabricate objects of my own design using components from multiple digital fabrication processes."]}

    ]

  end

end

app/controllers/standards_controller.rb
# frozen_string_literal: true
class StandardsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # TODO - PUT PUNDIT

  before_action :set_lesson, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  before_action :set_standards, only: [:new, :edit]
  before_action :set_lessons_standard, only: [:show, :edit, :update, :destroy]

  def index

    set_lesson_sections

    # Specify section as standards for use in sub nav
    @section = :standards

  end

  def new

    @lessons_standard_obj = LessonsStandard.new(lesson: @lesson_obj)

    # Assign the @form_step var, casting as integer instead of a string
    @form_step = params[:form_step].present? ? params[:form_step].to_i : 1

  end

  def edit

    # Assign the @form_step var, casting as integer instead of a string
    @form_step = params[:form_step].present? ? params[:form_step].to_i : 1

  end

  def create

    @lessons_standard_obj = LessonsStandard.new(lessons_standards_params)
    @lessons_standard_obj.lesson = @lesson_obj

    if @lessons_standard_obj.save
      redirect_to redirection, notice: "Your standard was successfully created."
    else
      render :new
    end

  end

  def update

    if @lessons_standard_obj.update(lessons_standards_params)
      redirect_to redirection, notice: 'Your standard information was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    
    # If the standard isn't found, return to index
    unless @lessons_standard_obj.present?
      redirect_to lesson_standards_path(lesson_id: @lesson_obj.id)
      return
    end

    # Destroy the step
    @lessons_standard_obj.destroy

    # Redirect to the lessons first step
    redirect_to new_lesson_standard_path(lesson_id: @lesson_obj.id), notice: 'Your standard was deleted.'

  end

  private

    def lessons_standards_params
      params.fetch(:lessons_standards).permit(:standard_id, :new_after_save, description: [])
    end

    def set_lessons_standard
      @lessons_standard_obj = LessonsStandard.includes(:standard).find_by(id: params[:id])
    end

    def redirection
      # Determine whether to just show the just-saved step, or create a new one
      redirection = lessons_standards_params[:new_after_save] == 'true' ? new_lesson_standard_path(lesson_id: @lesson_obj.id) : edit_lesson_standard_path(@lesson_obj, @lessons_standard_obj) 
    end

    def set_standards
      # Exclude any standards that have already been associated with this lesson
      @standards = @lesson_obj.standards.exists? ? Standard.where("id NOT IN (?)", @lesson_obj.standards.ids).all : Standard.all
    end

end

app/views/standards/_footer.html.erb
<div class="Form__footer">

  <div class="Form__footer__content">

    <div class="Form__footer__actions">
      <%= link_to "Back to Overview", edit_lesson_path(id: @lesson_obj.id, form_step: 1), class: 'Form__footer__action Button Button--primary Button--small Button--icon Button--icon--left Button--arrow--left' %>
      <%= link_to "Add some Details", edit_lesson_path(id: @lesson_obj.id, form_step: 3), class: 'Form__footer__action Button Button--primary Button--small Button--icon Button--icon--right Button--arrow--right' %>
    </div>

  </div>

</div>

app/views/standards/_form.html.erb
<%= field_set_tag nil, class: 'Form__fieldset' do %>

  <!-- lesson.standards -->
  <div class="FormFieldGroups FormFieldGroups--multiple">

    <div class="FormFieldGroup">

      <div class="FormField FormField--required">

        <div class="FormField__info">
          <label class="FormField__label" for="lessons_standards_standard_id">Standard</label>
          <div class="FormField__hint">Source and focus of this standard</div>
        </div>

        <div class="FormField__input">
          <select name="lessons_standards[standard_id]" id="lessons_standards_standard_id" required>
              <% unless @lessons_standard_obj.new_record? %>
              <option value="<%= @lessons_standard_obj.standard.id %>" data-autocomplete='<%= @lessons_standard_obj.standard.autocomplete.to_json %>' selected><%= @lessons_standard_obj.standard %></option>
              <% end %>
              <% @standards.each do |standard| %>
              <option value="<%= standard.id %>" data-autocomplete='<%= standard.autocomplete.to_json %>' <%= @lessons_standard_obj.present? ? (standard == @lessons_standard_obj.standard ? 'selected' : nil) : nil %>><%= standard %></option>
              <% end %>
          </select>
        </div>

      </div>

      <div class="FormField FormField--required">

        <div class="FormField__info">
          <label class="FormField__label" for="lessons_standards_description">Details</label>
          <div class="FormField__hint">Add one or more</div>
        </div>

        <div class="FormField__input FormField--multiple">
          <textarea name="lessons_standards[description][]" class="Input Input--multiple Input--autocomplete" placeholder="+ Add a new standard" id="lessons_standards_description_1"  data-values="<%= @lessons_standard_obj.present? ? @lessons_standard_obj.description.to_json : nil %>"></textarea>
        </div>

      </div>

    </div>

   <div class="FormField__actions">
    <button type="submit" class="Button Button--secondary FormField__action">Save standard</button>
    <input name="lessons_standards[new_after_save]" type="hidden" value="false" />
    <button type="submit" class="Button Button--secondary FormField__action FormField__action--new">Save and add a new standard</button>
  </div>

  </div>

<% end %>

app/views/standards/_standard_list.html.erb
<div class="EditList">

  <h3 class="EditList__heading">How does the learning align to educational standards?</h3>

  <div class="EditList__heading__sub">More info on SCOPESDF standards in Toolkit.</div>

  <ul class="EditList__items">
	<% @lesson_obj.lessons_standards.each_with_index do |lessons_standard, index| %>
	<li class="EditList__item">
		<div class="EditList__content">
        <div class="EditList__number">
          Standard <%= index + 1 %>
        </div>
        <div class="EditList__title">
          <%= lessons_standard.standard.name %>
        </div>
        <% if lessons_standard != @lessons_standard_obj %>
          <%= link_to "Edit standard", edit_lesson_standard_path(id: lessons_standard.id, lesson_id: @lesson_obj.id, form_step: @form_step), class: 'EditList__edit' %>
        <% else %>
          <%= link_to "Editing", edit_lesson_standard_path(id: lessons_standard.id, lesson_id: @lesson_obj.id, form_step: @form_step), class: 'EditList__edit EditList__edit--active' %>
        <% end %>
        <%= link_to '<span>Remove</span>'.html_safe, lesson_standard_path(id: lessons_standard.id, lesson_id: @lesson_obj.id, form_step: @form_step), method: :delete, confirm: "Are you sure?", class: 'EditList__remove' %>
      </div>
	</li>
	<% end %>
  </ul>
  <div class="EditList__actions">
    <%= link_to "+ Add a new standard", new_lesson_standard_path(lesson_id: @lesson_obj.id, form_step: @form_step) %>
  </div>

</div>

app/views/standards/edit.html.erb
<%= render partial: 'lessons/sub_header' %>

<%= render partial: 'lessons/edit_sub_nav' %>

<%= render partial: 'standards/standard_list' %>

<%= form_tag(lesson_standard_path(lesson_id: @lesson_obj.id, id: @lessons_standard_obj.id, form_step:2), method: :patch, class: "Form") do %>

  <%= render partial: "standards/form" %>

  <%= render partial: 'standards/footer' %>


<% end %>

app/views/standards/index.html.erb
<%= render partial: 'lessons/show_sub_nav' %>

<div class="PageHeader">
  <div class="PageHeader__content">
    <div class="PageHeader__title">
      <h1 class="PageHeader__heading"><%= @lesson_obj.name %></h1>
      <div class="PageHeader__sub">
        This lesson abides by the following standards
      </div>
    </div>
  </div>
</div>

<div class="StandardsIndex">

  <% @lesson_obj.lessons_standards.each do |lessons_standard| %>
  <div class="StandardsIndex__standard">

    <h3 class="StandardsIndex__heading">
      <%= lessons_standard.standard %>
    </h3>

    <ul class="StandardsIndex__descriptions">

      <% lessons_standard.description.each do |description| %>
      <li class="StandardsIndex__description">
        <%= description %>
      </li>
      <% end %>

    </ul>

  </div>
  <% end %>

</div>

<div class="PageFooter">

  <div class="PageFooter__content">

    <div class="PageFooter__actions">
      <%= link_to "Back to Overview", lesson_path(id: @lesson_obj.id), class: "PageFooter__action Button Button--primary Button--small Button--icon Button--icon--left Button--arrow--left" %>
      <%= link_to "Step by Step", lesson_steps_path(lesson_id: @lesson_obj.id), class: "PageFooter__action PageFooter__action--right Button Button--primary Button--small Button--icon Button--icon--right Button--arrow--right" %>
    </div>

  </div>

</div>

app/views/standards/new.html.erb
<%= render partial: 'lessons/sub_header' %>

<%= render partial: 'lessons/edit_sub_nav' %>

<%= render partial: 'standards/standard_list' %>

<%= form_tag(lesson_standards_path(lesson_id: @lesson_obj.id, form_step:2), method: :post, multipart: true, class: "Form") do %>

  <%= render partial: "standards/form" %>

  <%= render partial: 'standards/footer' %>

<% end %>